// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcvN2ubLUvi-80DchcXQvgFsG7DTT2-0c',
    appId: '1:33410031150:web:6a7a5f60c846eb3df809bf',
    messagingSenderId: '33410031150',
    projectId: 'findfurriend',
    authDomain: 'findfurriend.firebaseapp.com',
    storageBucket: 'findfurriend.firebasestorage.app',
    measurementId: 'G-PKV7K70PF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Gf50N9TyoYqEzV6g1YlEzLUyL7CHG7M',
    appId: '1:33410031150:android:01a07a932c859bd5f809bf',
    messagingSenderId: '33410031150',
    projectId: 'findfurriend',
    storageBucket: 'findfurriend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtGNy3tjiv9zXQQogxQpQjPEaeUG5Xhuo',
    appId: '1:33410031150:ios:aa953e2efad4abcef809bf',
    messagingSenderId: '33410031150',
    projectId: 'findfurriend',
    storageBucket: 'findfurriend.firebasestorage.app',
    iosBundleId: 'com.example.findfurriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtGNy3tjiv9zXQQogxQpQjPEaeUG5Xhuo',
    appId: '1:33410031150:ios:aa953e2efad4abcef809bf',
    messagingSenderId: '33410031150',
    projectId: 'findfurriend',
    storageBucket: 'findfurriend.firebasestorage.app',
    iosBundleId: 'com.example.findfurriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcvN2ubLUvi-80DchcXQvgFsG7DTT2-0c',
    appId: '1:33410031150:web:28b0de69e8b52d56f809bf',
    messagingSenderId: '33410031150',
    projectId: 'findfurriend',
    authDomain: 'findfurriend.firebaseapp.com',
    storageBucket: 'findfurriend.firebasestorage.app',
    measurementId: 'G-75Y8NFWRX6',
  );
}
